### ISSUE TITLE
ERROR in ./css/app.scss; Module parse failed: Unexpected character '@' (4:0)

### ISSUE THREAD

**Issue by Cate-Lukner** [dwyl/phoenix-todo-list-tutorial#43]
Hi, 

I was on section 3 for the Phoenix Todo List Tutorial, when I ran into the following error after running `mix phx.server`:
```
$ mix phx.server

[info] Running AppWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:4000 (http)
[info] Access AppWeb.Endpoint at http://localhost:4000

Webpack is watching the files…

Hash: 672a6b06bf1ab7a73560
Version: webpack 4.4.0
Time: 1107ms
Built at: 6/4/2020 9:03:26 AM
                Asset       Size       Chunks             Chunk Names
               app.js   7.43 KiB  ./js/app.js  [emitted]  ./js/app.js
        ../robots.txt  202 bytes               [emitted]
       ../favicon.ico   1.23 KiB               [emitted]
../images/phoenix.png   13.6 KiB               [emitted]
[../deps/phoenix_html/priv/static/phoenix_html.js] 2.21 KiB {./js/app.js} [built]
[./css/app.scss] 207 bytes {./js/app.js} [built] [failed] [1 error]
[./js/app.js] 494 bytes {./js/app.js} [built]
   [0] multi ./js/app.js 28 bytes {./js/app.js} [built]

ERROR in ./css/app.scss
Module parse failed: Unexpected character '@' (4:0)
You may need an appropriate loader to handle this file type.
| /* @import "./phoenix.css"; */
|
| @import "./todomvc-app.css";
 @ ./js/app.js 4:0-34
 @ multi ./js/app.js
```
When I try to connect to localhost:4000/items, the following happens in my command terminal:
```
mix phx.server
[info] Running AppWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:4000 (http)
[info] Access AppWeb.Endpoint at http://localhost:4000

Webpack is watching the files…

Hash: 672a6b06bf1ab7a73560
Version: webpack 4.4.0
Time: 1107ms
Built at: 6/4/2020 9:03:26 AM
                Asset       Size       Chunks             Chunk Names
               app.js   7.43 KiB  ./js/app.js  [emitted]  ./js/app.js
        ../robots.txt  202 bytes               [emitted]
       ../favicon.ico   1.23 KiB               [emitted]
../images/phoenix.png   13.6 KiB               [emitted]
[../deps/phoenix_html/priv/static/phoenix_html.js] 2.21 KiB {./js/app.js} [built]
[./css/app.scss] 207 bytes {./js/app.js} [built] [failed] [1 error]
[./js/app.js] 494 bytes {./js/app.js} [built]
   [0] multi ./js/app.js 28 bytes {./js/app.js} [built]

ERROR in ./css/app.scss
Module parse failed: Unexpected character '@' (4:0)
You may need an appropriate loader to handle this file type.
| /* @import "./phoenix.css"; */
|
| @import "./todomvc-app.css";
 @ ./js/app.js 4:0-34
 @ multi ./js/app.js
[info] GET /items
[debug] Processing with AppWeb.ItemController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[debug] QUERY OK source="items" db=1.6ms decode=2.2ms queue=1.4ms idle=1539.5ms
SELECT i0."id", i0."person_id", i0."status", i0."text", i0."inserted_at", i0."updated_at" FROM "items" AS i0 []
[info] Sent 500 in 111ms
[error] #PID<0.482.0> running AppWeb.Endpoint (connection #PID<0.481.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /items
** (exit) an exception was raised:
    ** (ArgumentError) assign @inner_content not available in eex template.

Please make sure all proper assigns have been set. If this
is a child template, ensure assigns are given explicitly by
the parent template as they are not automatically forwarded.

Available assigns: [:conn, :items, :view_module, :view_template]

        (phoenix_html 2.14.2) lib/phoenix_html/engine.ex:134: Phoenix.HTML.Engine.fetch_assign!/2
        (app 0.1.0) lib/app_web/templates/layout/app.html.eex:13: AppWeb.LayoutView."app.html"/1
        (phoenix 1.4.17) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
        (phoenix 1.4.17) lib/phoenix/controller.ex:776: Phoenix.Controller.__put_render__/5
        (phoenix 1.4.17) lib/phoenix/controller.ex:792: Phoenix.Controller.instrument_render_and_send/4
        (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.action/2
        (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.phoenix_controller_pipeline/2
        (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
        (app 0.1.0) lib/plug/debugger.ex:132: AppWeb.Endpoint."call (overridable 3)"/2
        (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
        (phoenix 1.4.17) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.8.0) /home/catluk/cate-lukner-internship/app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.8.0) /home/catluk/cate-lukner-internship/app/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
        (cowboy 2.8.0) /home/catluk/cate-lukner-internship/app/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
        (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
The follow error shows in my browser, which in turn does not allow the application to work. 
```
ArgumentError at GET /items
assign @inner_content not available in eex template.

Please make sure all proper assigns have been set. If this
is a child template, ensure assigns are given explicitly by
the parent template as they are not automatically forwarded.

Available assigns: [:conn, :items, :view_module, :view_template]
``` 
I am not an experienced programmer with CSS or Phoenix, so I am unsure even what question to ask. I've tried copy and pasting the code for each file to ensure accuracy. I know the following may be the clue: 
```
ERROR in ./css/app.scss
Module parse failed: Unexpected character '@' (4:0)
You may need an appropriate loader to handle this file type.
| /* @import "./phoenix.css"; */
|
| @import "./todomvc-app.css";
 @ ./js/app.js 4:0-34
 @ multi ./js/app.js
```
Since I do not have a lot of experience with CSS or Phoenix, when I try to google similar errors, the answers seem to go over my head and I am unsure how to apply solutions to my own error. Would anyone be able to help me in solving this error? 
Any help would be greatly appreciated!

**Comment by Cate-Lukner** [comment]
When I run `mix test`, I get the following test failures: 
```
ix test

09:15:06.705 [info]  Already up
..............

  1) test edit item renders form for editing chosen item (AppWeb.ItemControllerTest)
     test/app_web/controllers/item_controller_test.exs:49
     ** (ArgumentError) assign @inner_content not available in eex template.

     Please make sure all proper assigns have been set. If this
     is a child template, ensure assigns are given explicitly by
     the parent template as they are not automatically forwarded.

     Available assigns: [:changeset, :conn, :item, :view_module, :view_template]

     code: conn = get(conn, Routes.item_path(conn, :edit, item))
     stacktrace:
       (phoenix_html 2.14.2) lib/phoenix_html/engine.ex:134: Phoenix.HTML.Engine.fetch_assign!/2
       (app 0.1.0) lib/app_web/templates/layout/app.html.eex:13: AppWeb.LayoutView."app.html"/1
       (phoenix 1.4.17) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
       (phoenix 1.4.17) lib/phoenix/controller.ex:776: Phoenix.Controller.__put_render__/5
       (phoenix 1.4.17) lib/phoenix/controller.ex:792: Phoenix.Controller.instrument_render_and_send/4
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.action/2
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.phoenix_controller_pipeline/2
       (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
       (phoenix 1.4.17) lib/phoenix/test/conn_test.ex:235: Phoenix.ConnTest.dispatch/5
       test/app_web/controllers/item_controller_test.exs:50: (test)



  2) test update item redirects when data is valid (AppWeb.ItemControllerTest)
     test/app_web/controllers/item_controller_test.exs:58
     ** (ArgumentError) assign @inner_content not available in eex template.

     Please make sure all proper assigns have been set. If this
     is a child template, ensure assigns are given explicitly by
     the parent template as they are not automatically forwarded.

     Available assigns: [:conn, :item, :view_module, :view_template]

     code: conn = get(conn, Routes.item_path(conn, :show, item))
     stacktrace:
       (phoenix_html 2.14.2) lib/phoenix_html/engine.ex:134: Phoenix.HTML.Engine.fetch_assign!/2
       (app 0.1.0) lib/app_web/templates/layout/app.html.eex:13: AppWeb.LayoutView."app.html"/1
       (phoenix 1.4.17) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
       (phoenix 1.4.17) lib/phoenix/controller.ex:776: Phoenix.Controller.__put_render__/5
       (phoenix 1.4.17) lib/phoenix/controller.ex:792: Phoenix.Controller.instrument_render_and_send/4
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.action/2
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.phoenix_controller_pipeline/2
       (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
       (phoenix 1.4.17) lib/phoenix/test/conn_test.ex:235: Phoenix.ConnTest.dispatch/5
       test/app_web/controllers/item_controller_test.exs:62: (test)



  3) test index lists all items (AppWeb.ItemControllerTest)
     test/app_web/controllers/item_controller_test.exs:16
     ** (ArgumentError) assign @inner_content not available in eex template.

     Please make sure all proper assigns have been set. If this
     is a child template, ensure assigns are given explicitly by
     the parent template as they are not automatically forwarded.

     Available assigns: [:conn, :items, :view_module, :view_template]

     code: conn = get(conn, Routes.item_path(conn, :index))
     stacktrace:
       (phoenix_html 2.14.2) lib/phoenix_html/engine.ex:134: Phoenix.HTML.Engine.fetch_assign!/2
       (app 0.1.0) lib/app_web/templates/layout/app.html.eex:13: AppWeb.LayoutView."app.html"/1
       (phoenix 1.4.17) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
       (phoenix 1.4.17) lib/phoenix/controller.ex:776: Phoenix.Controller.__put_render__/5
       (phoenix 1.4.17) lib/phoenix/controller.ex:792: Phoenix.Controller.instrument_render_and_send/4
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.action/2
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.phoenix_controller_pipeline/2
       (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
       (phoenix 1.4.17) lib/phoenix/test/conn_test.ex:235: Phoenix.ConnTest.dispatch/5
       test/app_web/controllers/item_controller_test.exs:17: (test)



  4) test create item redirects to show when data is valid (AppWeb.ItemControllerTest)
     test/app_web/controllers/item_controller_test.exs:30
     ** (ArgumentError) assign @inner_content not available in eex template.

     Please make sure all proper assigns have been set. If this
     is a child template, ensure assigns are given explicitly by
     the parent template as they are not automatically forwarded.

     Available assigns: [:conn, :item, :view_module, :view_template]

     code: conn = get(conn, Routes.item_path(conn, :show, id))
     stacktrace:
       (phoenix_html 2.14.2) lib/phoenix_html/engine.ex:134: Phoenix.HTML.Engine.fetch_assign!/2
       (app 0.1.0) lib/app_web/templates/layout/app.html.eex:13: AppWeb.LayoutView."app.html"/1
       (phoenix 1.4.17) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
       (phoenix 1.4.17) lib/phoenix/controller.ex:776: Phoenix.Controller.__put_render__/5
       (phoenix 1.4.17) lib/phoenix/controller.ex:792: Phoenix.Controller.instrument_render_and_send/4
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.action/2
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.phoenix_controller_pipeline/2
       (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
       (phoenix 1.4.17) lib/phoenix/test/conn_test.ex:235: Phoenix.ConnTest.dispatch/5
       test/app_web/controllers/item_controller_test.exs:36: (test)



  5) test update item renders errors when data is invalid (AppWeb.ItemControllerTest)
     test/app_web/controllers/item_controller_test.exs:66
     ** (ArgumentError) assign @inner_content not available in eex template.

     Please make sure all proper assigns have been set. If this
     is a child template, ensure assigns are given explicitly by
     the parent template as they are not automatically forwarded.

     Available assigns: [:changeset, :conn, :item, :view_module, :view_template]

     code: conn = put(conn, Routes.item_path(conn, :update, item), item: @invalid_attrs)
     stacktrace:
       (phoenix_html 2.14.2) lib/phoenix_html/engine.ex:134: Phoenix.HTML.Engine.fetch_assign!/2
       (app 0.1.0) lib/app_web/templates/layout/app.html.eex:13: AppWeb.LayoutView."app.html"/1
       (phoenix 1.4.17) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
       (phoenix 1.4.17) lib/phoenix/controller.ex:776: Phoenix.Controller.__put_render__/5
       (phoenix 1.4.17) lib/phoenix/controller.ex:792: Phoenix.Controller.instrument_render_and_send/4
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.action/2
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.phoenix_controller_pipeline/2
       (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
       (phoenix 1.4.17) lib/phoenix/test/conn_test.ex:235: Phoenix.ConnTest.dispatch/5
       test/app_web/controllers/item_controller_test.exs:67: (test)



  6) test new item renders form (AppWeb.ItemControllerTest)
     test/app_web/controllers/item_controller_test.exs:23
     ** (ArgumentError) assign @inner_content not available in eex template.

     Please make sure all proper assigns have been set. If this
     is a child template, ensure assigns are given explicitly by
     the parent template as they are not automatically forwarded.

     Available assigns: [:changeset, :conn, :view_module, :view_template]

     code: conn = get(conn, Routes.item_path(conn, :new))
     stacktrace:
       (phoenix_html 2.14.2) lib/phoenix_html/engine.ex:134: Phoenix.HTML.Engine.fetch_assign!/2
       (app 0.1.0) lib/app_web/templates/layout/app.html.eex:13: AppWeb.LayoutView."app.html"/1
       (phoenix 1.4.17) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
       (phoenix 1.4.17) lib/phoenix/controller.ex:776: Phoenix.Controller.__put_render__/5
       (phoenix 1.4.17) lib/phoenix/controller.ex:792: Phoenix.Controller.instrument_render_and_send/4
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.action/2
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.phoenix_controller_pipeline/2
       (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
       (phoenix 1.4.17) lib/phoenix/test/conn_test.ex:235: Phoenix.ConnTest.dispatch/5
       test/app_web/controllers/item_controller_test.exs:24: (test)



  7) test create item renders errors when data is invalid (AppWeb.ItemControllerTest)
     test/app_web/controllers/item_controller_test.exs:40
     ** (ArgumentError) assign @inner_content not available in eex template.

     Please make sure all proper assigns have been set. If this
     is a child template, ensure assigns are given explicitly by
     the parent template as they are not automatically forwarded.

     Available assigns: [:changeset, :conn, :view_module, :view_template]

     code: conn = post(conn, Routes.item_path(conn, :create), item: @invalid_attrs)
     stacktrace:
       (phoenix_html 2.14.2) lib/phoenix_html/engine.ex:134: Phoenix.HTML.Engine.fetch_assign!/2
       (app 0.1.0) lib/app_web/templates/layout/app.html.eex:13: AppWeb.LayoutView."app.html"/1
       (phoenix 1.4.17) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
       (phoenix 1.4.17) lib/phoenix/controller.ex:776: Phoenix.Controller.__put_render__/5
       (phoenix 1.4.17) lib/phoenix/controller.ex:792: Phoenix.Controller.instrument_render_and_send/4
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.action/2
       (app 0.1.0) lib/app_web/controllers/item_controller.ex:1: AppWeb.ItemController.phoenix_controller_pipeline/2
       (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
       (phoenix 1.4.17) lib/phoenix/test/conn_test.ex:235: Phoenix.ConnTest.dispatch/5
       test/app_web/controllers/item_controller_test.exs:41: (test)

.

  8) test GET / (AppWeb.PageControllerTest)
     test/app_web/controllers/page_controller_test.exs:4
     ** (ArgumentError) assign @inner_content not available in eex template.

     Please make sure all proper assigns have been set. If this
     is a child template, ensure assigns are given explicitly by
     the parent template as they are not automatically forwarded.

     Available assigns: [:conn, :view_module, :view_template]

     code: conn = get(conn, "/")
     stacktrace:
       (phoenix_html 2.14.2) lib/phoenix_html/engine.ex:134: Phoenix.HTML.Engine.fetch_assign!/2
       (app 0.1.0) lib/app_web/templates/layout/app.html.eex:13: AppWeb.LayoutView."app.html"/1
       (phoenix 1.4.17) lib/phoenix/view.ex:410: Phoenix.View.render_to_iodata/3
       (phoenix 1.4.17) lib/phoenix/controller.ex:776: Phoenix.Controller.__put_render__/5
       (phoenix 1.4.17) lib/phoenix/controller.ex:792: Phoenix.Controller.instrument_render_and_send/4
       (app 0.1.0) lib/app_web/controllers/page_controller.ex:1: AppWeb.PageController.action/2
       (app 0.1.0) lib/app_web/controllers/page_controller.ex:1: AppWeb.PageController.phoenix_controller_pipeline/2
       (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
       (app 0.1.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
       (phoenix 1.4.17) lib/phoenix/test/conn_test.ex:235: Phoenix.ConnTest.dispatch/5
       test/app_web/controllers/page_controller_test.exs:5: (test)



Finished in 0.4 seconds
23 tests, 8 failures

Randomized with seed 844132
```

**Comment by nelsonic** [comment]
@Cate-Lukner thanks for opening this issue to report your experience.
are you seeing this error for the _finished_ app cloned from this repo?
Or for the app you are building from scratch following the tutorial?

Either way, can you please confirm which version of Node.js you are running?
In your terminal run:
```
node -v
```

**Comment by Cate-Lukner** [comment]
Just to confirm I now have 1.5.3:
```
$ mix phx.new -v
Phoenix v1.5.3
```

**Comment by nelsonic** [comment]
@Cate-Lukner good question. You _can_ continue from where you are if you follow the upgrade instructions: https://gist.github.com/chrismccord/e53e79ef8b34adf5d8122a47db44d22f
But honestly, if you want to save yourself the headache, just do it from scratch. 💭

**Comment by Cate-Lukner** [comment]
Ok, thank you! I will try doing to upgrade instructions since that might help me learn a few more things. If all else fails, I will just do it from scratch.

**Comment by nelsonic** [comment]
That's a _great_ mindset! It is a good way to learn the differences and understand how straightforward it is to apply the update. 👍 
When you succeed, feel free to close this issue. ✅ 
And if you find the tutorial useful, please give it a ⭐ on GitHub to help others discover it.

**Comment by Cate-Lukner** [comment]
Ok will do!

**Comment by nelsonic** [comment]
By the way, how/where did you find this tutorial? (_if you don't mind us asking ..._) 🙂

**Comment by Cate-Lukner** [comment]
@nelsonic Sorry, just saw your comment now. I found it via my computer science professor, he is having me learn Phoenix so he recommended me this tutorial.

**Comment by nelsonic** [comment]
@Cate-Lukner amazing! Tell your prof we're stoked he is recommending Phoenix and our tutorial(s) in particular! 🙌 
Thanks again for opening this issue and all your input. This is _why_ we do what we do. ✅ ❤️ 
Hope you have a great day! ☀️
