### ISSUE TITLE
Heroku App Crashed

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-todo-list-tutorial#47]
https://phxtodo.herokuapp.com
![image](https://user-images.githubusercontent.com/194400/112019765-a7cac000-8b27-11eb-9af7-0f3cb6ae02ed.png)

`503` errors ... https://dashboard.heroku.com/apps/phxtodo/logs
![image](https://user-images.githubusercontent.com/194400/112019411-51f61800-8b27-11eb-8097-9268440e533d.png)

**Comment by nelsonic** [comment]
Attempted to run:
```
heroku run "POOL_SIZE=2 mix ecto.create"
```

Got:
```
 ›   Warning: heroku update available from 7.43.2 to 7.59.0.
Running POOL_SIZE=2 mix ecto.create on ⬢ phxtodo... up, run.1429 (Free)

23:04:09.218 [error] GenServer #PID<0.251.0> terminating
** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) no pg_hba.conf entry for host "52.49.145.255", user "twbcdorjceoeak", database "postgres", SSL off
    (db_connection 2.2.2) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for App.Repo couldn't be created: killed
```

> Note: the `user` is no longer valid, I reset it. But the error persists. 😕

**Comment by nelsonic** [comment]
```
$ heroku update
heroku: Updating CLI from 7.43.2 to 7.59.0... ⣯ 6.6 MB/29.5 MB
```

**Comment by nelsonic** [comment]
Heroku config for Phoenix apps has changed: https://hexdocs.pm/phoenix/heroku.html

**Comment by nelsonic** [comment]
```
-----> Installing Hex
* creating /tmp/build_305ffe64/.mix/archives/hex-0.21.2
-----> Installing rebar
* creating /tmp/build_305ffe64/.mix/rebar
* creating /tmp/build_305ffe64/.mix/rebar3
-----> Fetching app dependencies with mix
** (SyntaxError) config/prod.exs:15: syntax error before: http
    (elixir 1.10.4) lib/code.ex:340: Code.eval_string_with_error_handling/3
    (mix 1.10.4) lib/mix/config.ex:158: anonymous fn/2 in Mix.Config.__import__!/2
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.10.4) lib/mix/config.ex:157: Mix.Config.__import__!/2
    (stdlib 3.11.2) erl_eval.erl:680: :erl_eval.do_apply/6
 !     Push rejected, failed to compile Elixir app.
 !     Push failed
```

**Comment by nelsonic** [comment]
Working again! 
![image](https://user-images.githubusercontent.com/194400/133346830-eb9afa06-0a8a-43ea-8e3a-8dba3fe9899d.png)
